config/routes.rb
Rails.application.routes.draw do

  get "welcome/download_pdf"

  root 'welcome#index'

  resources :users

  resources :layouts

end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'Usuario actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :bio, :twuser, :ghuser, :guser, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@user = User.last

  	unless @user

  		redirect_to new_user_path
  	end
  end

	def download_pdf
	  send_file("#{Rails.root}/public/data/rfz.pdf",
	    filename: "rfz.pdf",
	    type: "application/pdf")
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_title(separator = " | ")
	  [content_for(:title), 'Currículum'].compact.join(separator)
	end

	def page_heading(title)
	  content_for(:title){ title }
	  content_tag(:h1, title)
	end
	def title
  	h(@title_full ? @title_full : [@title_prefix, "Currículum"].compact.join(' | '))
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <%= favicon_link_tag @user.avatar %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="background">
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
            <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand page-scroll" href="#about">
            <i class="fa fa-play-circle"></i>  <span class="light">Ing. </span> 
            <strong>
              <% if @user != nil %>
                <%= @user.name %>
              <% else %>
                <%= "Anyelo Josue" %>
              <% end %>
            </strong>
          </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
            <li>    
              <a class="page-scroll" href="/#">Inicio</a>
            </li>
            <li>
              <a class="page-scroll" href="/#about">Sobre mí</a>
            </li>
            <li>
              <a class="page-scroll" href="/#download">Descargar</a>
            </li>
            <li>
              <a class="page-scroll" href="/#contact">Contáctame</a>
            </li>
            <li>
            <a href="/users/<%= @user.id if @user %>/edit">Editar Usuario </a> 
            </li>
          </ul>
        </div>
      </div>
    </nav>

  	<%= yield %>
  	
    <footer class="text-center">
      <p>Copyright &copy; Your Website 2016</p>
    </footer>
  </div>
</body>
</html>

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohíben a este usuario ser guardado:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>

  <div class="row">
    <form>
      <div class="datos col-lg-6 col-xs-6">
        <div class="form-group">
            <div class="field">
              <%= f.label :nombre %><br>
              <%= f.text_field :name, class: "form-control col-lg-12 col-md-12", type: "text", placeholder: "Nombre a mostrar" %>
            </div>
        </div>
        <div class="form-group">
            <div class="field">
              <label for="exampleInputEmail3">Correo Electrónico</label>
              <%= f.text_field :email, class: "form-control col-lg-12 col-md-12", type: "text", placeholder: "correo@ejemplo.com" %>
            </div>
        </div>

        <div class="form-group">
          <div class="field">
              <label for="exampleInputEmail3">Biografía</label>
            <%= f.text_area :bio, class: "form-control col-lg-12 col-md-12", rows: "3" %>
          </div>
        </div>
        <div class="field" id="#upload_image">
          <br>
          <%= f.label :avatar %>
          <%= f.file_field :avatar, value: "Examinar" %>
        </div>
      </div>
      <div class="social col-lg-6 col-xs-6">
        <div class="form-group">
          <label for="exampleInputAmount">Twitter</label>
          <div class="input-group">
            <div class="input-group-addon">@</div>
              <%= f.text_field :twuser, class: "form-control", type: "text", placeholder: "Usuario" %>
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputAmount">Github</label>
          <div class="input-group">
            <div class="input-group-addon">@</div>
              <%= f.text_field :ghuser, class: "form-control", type: "text", placeholder: "Usuario" %>
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputAmount">Google +</label>
          <div class="input-group">
            <div class="input-group-addon">@</div>
              <%= f.text_field :guser, class: "form-control", type: "text", placeholder: "Usuario" %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit 'Acceder', class: "btn btn-primary form-inline" %> 
        </div>
      </div>      

    </form>
  </div>

<% end %>

app/views/users/edit.html.erb
<section class="show">
  <h1>Editar Usuario</h1>

	  <%= render "form" %>


</section>

app/views/users/index.html.erb
<section class="show">
    <p id="notice"><%= notice %></p>
<section class="show">

app/views/users/new.html.erb
<section class="show">

	<h1>Nuevo Usuario</h1>

    <%= render "form" %>
	
</section>

app/views/users/show.html.erb
<section class="show">
		<p id="notice"><%= notice %></p>

</section>

app/views/welcome/index.html.erb
<div class="index">
  <!-- Navigation -->
    <!-- Intro Header -->
    <header class="intro">
      <div class="intro-body">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1 class="brand-heading">Currículum</h1>
                <p class="intro-text">"Measuring programming progress by lines of code is like measuring aircraft building progress by weight".<br> - Bill Gates.</p>
                <a href="/#about" class="btn btn-circle page-scroll">
                  <i class="fa fa-angle-double-down animated"></i>
                </a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <%= image_tag(@user.avatar, class: "avatar img-circle")%>
            <h2>Sobre mí</h2>
            <% if @user != nil %>
              <%= @user.bio %>
            <% else %>
              <p> Nacido en Julio de 1996, Técnico Medio en Servicios Administrativos mención Informática, cursando 4to semestre de Ingeniería de Sistemas y músico mixto. Puedes escuchar mi material en <a href="http://soundcloud.com/anyelo-petit/">este enlace</a>. Pasantías escolares realizadas en PDVSA: sede Cardón, en el área de Telecomunicaciones e Informática.</p>
            <% end %>
            
        </div>
      </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
      <div class="download-section">
        <div class="container">
          <div class="col-lg-8 col-lg-offset-2">
            <h2>Descargar Currículum</h2>
            <p>Puedes descargar este currículum digital en el siguiente enlace: </p>
            <%= link_to 'Descargar', welcome_download_pdf_url, class:"btn btn-default btn-lg" %>
          </div>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <h2>Contáctame</h2>
          <p>¡Siéntete libre de enviar tus comentarios, sugerencias o un simple "hola"!</p>
          <p><a href="mailto:<%= @user.email  %>"><%= @user.email %></a></p>
          <ul class="list-inline banner-social-buttons">
            <li class="social-btn">
              <a href="https://twitter.com/<%= @user.twuser %>" class="twitter btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
            </li>
            <li class="social-btn">
              <a href="https://github.com/<%= @user.ghuser %>" class="github btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
            </li>
            <li class="social-btn">
              <a href="https://plus.google.com/<%= @user.guser %>" class="google btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
            </li>
          </ul>
        </div>
      </div>
    </section>
</div>